Repository ucsb-cs156-s25/proj-courses-s25-01, pull requests merged in 2025-05, with the labels that each got.

#22 as - add placeholder for GESearchPage
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/GeneralEducation/GeneralEducationSearchPage.js
  frontend/src/tests/pages/GeneralEducation/GeneralEducationSearchPage.test.js
Labels: 5, Merge Candidate-CI

#27 eyobte - create a API Endpoint for GE Information
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: 10, Merge Candidate-Dokku, Ready-For-Staff

#25 hj - pagniate jobs for backend
  src/main/java/edu/ucsb/cs156/courses/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/courses/repositories/JobsRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/JobsControllerTests.java
Labels: 10

#29 as - GeneralEducationSearchForm and Tests
  frontend/src/main/components/GeneralEducation/GeneralEducationSearchForm.js
  frontend/src/stories/components/GeneralEducation/GeneralEducationSearchForm.stories.js
  frontend/src/tests/components/GeneralEducation/GeneralEducationSearchForm.test.js
Labels: 10, Merge Candidate-CI

#32 as - added tests to remove large stryker exception
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 10, Merge Candidate-CI

#30 add classroom dropdown
  frontend/src/fixtures/classroomFixtures.js
  frontend/src/main/components/Classrooms/SingleClassroomDropdown.js
  frontend/src/stories/components/Classrooms/SingleClassroomDropdown.stories.js
  frontend/src/tests/components/Classrooms/SingleClassroomDropdown.test.js
  frontend/src/tests/pages/SectionSearches/SectionSearchesIndexPage.test.js
Labels: FIXME-Team CR
